services:
  - type: web
    name: craverush-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
